config/routes.rb
Rails.application.routes.draw do
  resources :contributions
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contributions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 140}
  validates :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :contributions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.paginate(page: params[:page])
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to @contribution, notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:title, :url, :points, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @contributions = @user.contributions.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/_contribution.html.erb
<li id="contribution-<%= contribution.id %>">
  <span class="title"><%= contribution.title %></span>
  (<span class="url"><%= contribution.url %></span>)
  <br>
  <span class="points"><%= contribution.points %> points</span>
  <span class="user">by <%= link_to contribution.user.name, contribution.user %></span>
  <span class="timestamp">
    <%= time_ago_in_words(contribution.created_at) %> ago
  </span>
</li>

app/views/contributions/_form.html.erb
<%= form_with(model: contribution, local: true) do |form| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <p>Aquest camp esta aqui perque encara no hi ha login implementat</p>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<ol class="contributions">
  <%= render @contributions %>
</ol>
<%= will_paginate%>


<p id="notice"><%= notice %></p>

app/views/contributions/new.html.erb
<h1>Submit</h1>

<%= render 'form', contribution: @contribution %>

app/views/contributions/newview.html.erb
<p id="notice"><%= notice %></p>

<h1>Hacker News - New</h1>
<%= link_to 'Submit',  %>

<ol class="contributions">
  <%= render @contributions %>
</ol>
<%= will_paginate%>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contribution.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @contribution.url %>
</p>

<p>
  <strong>Points:</strong>
  <%= @contribution.points %>
</p>

<p>
  <strong>User:</strong>
  <%= @contribution.user.name %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackernews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
      <div class="header">
        <a><img src="<%= image_path('icono.png') %>" /></a>
        <a><b><%= link_to "Hacker News", contributions_path, id: "logo" %></b></a>
            <a><%= link_to "new", contributions_path %></a>
            <a> | </a>
            <a><%= link_to "comments",   '#' %></a>
            <a> | </a>
            <a><%= link_to "show",   '#' %></a>
            <a> | </a>
            <a><%= link_to "ask",   '#' %></a>
            <a> | </a>
            <a><%= link_to "jobs",   '#' %></a>
            <a> | </a>
            <a><%= link_to 'submit', new_contribution_path %></a>
            <a> | </a>
            <a><%= link_to "login", '#' %></a>
        </div>
        <div class="container">
        <%= yield %>
        </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= will_paginate %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>